openapi: 3.0.3
info:
  title: Product Prices Microservice
  description: Microservice that provides product prices
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/api/v1'
paths:
  /product-prices:
    get:
      description: Returns product price details
      parameters:
        - name: productId
          in: query
          description: Product ID
          required: true
          schema:
            type: integer
            example: 35455
        - name: brandId
          in: query
          description: Brand ID
          required: true
          schema:
            type: integer
            example: 1
        - name: date
          in: query
          description: Date and time
          required: true
          schema:
            type: string
            example: 2020-06-14-00.00.00
      responses:
        '200':
          $ref: '#/components/responses/ProductPriceResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
components:
  responses:
    ProductPriceResponse:
      description: Product price details
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProductPrice'
    BadRequestResponse:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFoundResponse:
      description: Product not found
  schemas:
    ProductPrice:
      type: object
      required:
        - productId
        - brandId
        - rate
        - startDate
        - endDate
        - price
        - currency
      properties:
        productId:
          type: integer
          example: 35455
        brandId:
          type: integer
          example: 1
        rate:
          type: integer
          example: 1
        startDate:
          type: string
          example: 2020-06-14-00.00.00
        endDate:
          type: string
          example: 2020-06-14-00.00.00
        price:
          type: number
          example: 35.50
        currency:
          type: string
          example: EUR
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: Parameter [date] is invalid
